import { NextRequest, NextResponse } from "next/server";

const airports = [
  { iata: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
  { iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
  { iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", city: "Madrid", country: "Spain" },
  { iata: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona", country: "Spain" },
  { iata: "FCO", name: "Leonardo da Vinci International Airport", city: "Rome", country: "Italy" },
  { iata: "MXP", name: "Malpensa Airport", city: "Milan", country: "Italy" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
  { iata: "ZUR", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway" },
  { iata: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
  { iata: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
  { iata: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { iata: "PRG", name: "Václav Havel Airport", city: "Prague", country: "Czech Republic" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary" },
  { iata: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { iata: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "United States" },
  { iata: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "United States" },
  { iata: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "United States" },
  { iata: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "United States" },
  { iata: "MIA", name: "Miami International Airport", city: "Miami", country: "United States" },
  { iata: "BOS", name: "Logan International Airport", city: "Boston", country: "United States" },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "United States" },
  { iata: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "United States" },
  { iata: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "United States" },
  { iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
  { iata: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
  { iata: "YUL", name: "Montréal-Trudeau International Airport", city: "Montreal", country: "Canada" },
  { iata: "MEX", name: "Benito Juárez International Airport", city: "Mexico City", country: "Mexico" },
  { iata: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo", country: "Brazil" },
  { iata: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina" },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia" },
  { iata: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru" },
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "UAE" },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia" },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia" },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait" },
  { iata: "BAH", name: "Bahrain International Airport", city: "Manama", country: "Bahrain" },
  { iata: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "India" },
  { iata: "BLR", name: "Kempegowda International Airport", city: "Bangalore", country: "India" },
  { iata: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", country: "India" },
  { iata: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India" },
  { iata: "COK", name: "Cochin International Airport", city: "Kochi", country: "India" },
  { iata: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad", country: "India" },
  { iata: "PNQ", name: "Pune Airport", city: "Pune", country: "India" },
  { iata: "GOI", name: "Goa International Airport", city: "Goa", country: "India" },
  { iata: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram", country: "India" },
  { iata: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal" },
  { iata: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka" },
  { iata: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh" },
  { iata: "KHI", name: "Jinnah International Airport", city: "Karachi", country: "Pakistan" },
  { iata: "LHE", name: "Allama Iqbal International Airport", city: "Lahore", country: "Pakistan" },
  { iata: "ISB", name: "Islamabad International Airport", city: "Islamabad", country: "Pakistan" },
  { iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
  { iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
  { iata: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong" },
  { iata: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
  { iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { iata: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { iata: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { iata: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand" },
  { iata: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia" },
  { iata: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
  { iata: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam" },
  { iata: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam" },
  { iata: "RGN", name: "Yangon International Airport", city: "Yangon", country: "Myanmar" },
  { iata: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", country: "Cambodia" },
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco" },
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
  { iata: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa" },
  { iata: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
  { iata: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa", country: "Ethiopia" },
  { iata: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria" },
  { iata: "ACC", name: "Kotoka International Airport", city: "Accra", country: "Ghana" },
  { iata: "TUN", name: "Tunis-Carthage International Airport", city: "Tunis", country: "Tunisia" },
  { iata: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { iata: "SAW", name: "Sabiha Gökçen International Airport", city: "Istanbul", country: "Turkey" },
  { iata: "TLV", name: "Ben Gurion International Airport", city: "Tel Aviv", country: "Israel" },
  { iata: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "Jordan" },
  { iata: "BEY", name: "Beirut Rafic Hariri International Airport", city: "Beirut", country: "Lebanon" },
  { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { iata: "LUX", name: "Luxembourg Airport", city: "Luxembourg", country: "Luxembourg" },
  { iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { iata: "TXL", name: "Berlin Tegel Airport", city: "Berlin", country: "Germany" },
  { iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
  { iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany" },
  { iata: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { iata: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France" },
  { iata: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
  { iata: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom" },
  { iata: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom" },
  { iata: "LTN", name: "Luton Airport", city: "London", country: "United Kingdom" },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom" },
  { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom" },
  { iata: "EWR", name: "Newark Liberty International Airport", city: "New York", country: "United States" },
  { iata: "LGA", name: "LaGuardia Airport", city: "New York", country: "United States" },
  { iata: "IAD", name: "Dulles International Airport", city: "Washington DC", country: "United States" },
  { iata: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington DC", country: "United States" },
  { iata: "IAH", name: "George Bush Intercontinental Airport", city: "Houston", country: "United States" },
  { iata: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "United States" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "United States" },
  { iata: "DTW", name: "Detroit Metropolitan Airport", city: "Detroit", country: "United States" },
  { iata: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "United States" },
  { iata: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", country: "United States" },
  { iata: "DEN", name: "Denver International Airport", city: "Denver", country: "United States" },
  { iata: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "United States" },
  { iata: "MCO", name: "Orlando International Airport", city: "Orlando", country: "United States" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "United States" },
  { iata: "TPA", name: "Tampa International Airport", city: "Tampa", country: "United States" },
  { iata: "PDX", name: "Portland International Airport", city: "Portland", country: "United States" },
  { iata: "SAN", name: "San Diego International Airport", city: "San Diego", country: "United States" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International Airport", city: "New Orleans", country: "United States" },
  { iata: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", country: "United States" },
  { iata: "BWI", name: "Baltimore/Washington International Airport", city: "Baltimore", country: "United States" },
  { iata: "MCI", name: "Kansas City International Airport", city: "Kansas City", country: "United States" },
  { iata: "CLE", name: "Cleveland Hopkins International Airport", city: "Cleveland", country: "United States" },
  { iata: "IND", name: "Indianapolis International Airport", city: "Indianapolis", country: "United States" },
  { iata: "CMH", name: "John Glenn Columbus International Airport", city: "Columbus", country: "United States" },
  { iata: "PIT", name: "Pittsburgh International Airport", city: "Pittsburgh", country: "United States" },
  { iata: "MEM", name: "Memphis International Airport", city: "Memphis", country: "United States" },
  { iata: "STL", name: "St. Louis Lambert International Airport", city: "St. Louis", country: "United States" },
  { iata: "RDU", name: "Raleigh-Durham International Airport", city: "Raleigh", country: "United States" },
  { iata: "BNA", name: "Nashville International Airport", city: "Nashville", country: "United States" },
  { iata: "AUS", name: "Austin-Bergstrom International Airport", city: "Austin", country: "United States" },
  { iata: "SAT", name: "San Antonio International Airport", city: "San Antonio", country: "United States" },
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get("q")?.toLowerCase() ?? "";

  if (query.length < 2) {
    return NextResponse.json([]);
  }

  const results = airports.filter(
    (a) =>
      a.iata.toLowerCase().includes(query) ||
      a.name.toLowerCase().includes(query) ||
      a.city.toLowerCase().includes(query) ||
      a.country.toLowerCase().includes(query)
  ).slice(0, 8);

  return NextResponse.json(results);
}